### PR TITLE
IE8 support

### PR DESCRIPTION
**Pull request by givankin**
IE8 chokes on direct call to `Array#indexOf` call. Substituted it with `lodash.indexOf`.

### CODE REVIEW

**Comment by mvhenten** [comment]
Will publish an updated version tonight.

**Comment by givankin** [comment]
Awesome, thanks

**Comment by givankin** [comment]
Hi @mvhenten. Did you have a chance to update the lib on npm?

**Comment by mvhenten** [comment]
I think so ... "*0.0.8 \* last updated 7 hours ago"

All tests passed so I just bumped version.

On Thu, May 22, 2014 at 1:34 PM, Georgiy Ivankin
notifications@github.comwrote:

> Hi @mvhenten https://github.com/mvhenten. Did you have a chance to
> update the lib on npm?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mvhenten/validate-arguments-js/pull/6#issuecomment-43876373
> .

## 

webdeveloper & consultant @technischepartij.nl
Mobile: +31 (0)630841238

Retiefstraat 51-III
1092VX Amsterdam
The Netherlands

**Comment by givankin** [comment]
Oh yes I see it on npm. It's just `package.json` in the repo is still with 0.0.7, probably should be updated too. Cheers!

**Comment by mvhenten** [comment]
aight, forgot the git-push. sorry, working between a million things right
now :)

On Thu, May 22, 2014 at 8:47 PM, Georgiy Ivankin
notifications@github.comwrote:

> Oh yes I see it on npm. It's just package.json in the repo is still with
> 0.0.7, probably should be updated too. Cheers!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mvhenten/validate-arguments-js/pull/6#issuecomment-43928277
> .

## 

webdeveloper & consultant @technischepartij.nl
Mobile: +31 (0)630841238

Retiefstraat 51-III
1092VX Amsterdam
The Netherlands

**Pull request merged**
