### PR TITLE
fixes #2 (support for underscore.js)

### LINKED ISSUE #2: Support underscore.js
I'd like to use `validate-arguments` in my browser app where I already have underscore, however, it misses the `isPlainObject` method.
It can be easily simulated using other underscore's methods. Would you mind a pull request on this?

### PR DESCRIPTION
**Pull request by givankin**
Fixes support for `underscore.js` instead of `lodash.js` by mimicking the missing `isPlainObject` method.

### CODE REVIEW

**Comment by mvhenten** [comment]
Hi, implementation is looks good, can you put it onto a topic branch (
"issue-3-is-plain-object" )?

Preferably it should go into the `typeConstraints` hash as a custom
implementation, you don't need to mock lodash & extend the global _ that
way.
I can fix that if you put it on a issue branch.

**Comment by givankin** [comment]
Well sorry I don't quite get it. It's in an issue branch in my fork ("issue-2-support-underscorejs") but there seems to be no way to submit this pull request to a separate branch in _your_ repository.

**Comment by mvhenten** [comment]
I'm not too fluent with pull request either. let me dig into it

**Comment by mvhenten** [comment]
I'm accepting your pull and add some changes building on that idea

**Comment by givankin** [comment]
Awesome.

**Comment by mvhenten** [comment]
I've made one alteration: I now rely on your plainObject for the whole
implementation without touching `_`.
Only one code path to worry about.

**Comment by givankin** [comment]
The issue is there again: https://github.com/mvhenten/validate-arguments-js/blob/master/lib/validate.js#L17
`_.isPlainObject` is used instead of `Types.isPlainObject`

**Comment by mvhenten** [comment]
Arg!
You are absolutely right, I missed that one. Should have been
"Types.isPlainObject". lodash is just too embedded in my brain.
Will fix, thanks

**Pull request merged**
