### PR TITLE
can ommit "isa" key in spec object

### PR DESCRIPTION
**Pull request by givankin**
When using the library I found myself creating lots of large validation objects typically looking like

```
{
    message: {
        isa: 'object'
    },
    author: {
        isa: 'object'
    },
    id: {
        isa: 'natural'
    },
    ts: {
        isa: 'number'
    }
}
```

This is great, but a bit too verbose, especially if there are lots of such code in one file. So I'd like to write it like this:

```
{
    message: 'object',
    author: 'object',
    id: 'natural',
    ts: 'number'
}
```

I've added a simple test, which doesn't cover all the scenarios, but I'd like to share the idea and know what you think. If that doesn't conflict with your vision, I can polish the pull request.

### CODE REVIEW

**Comment by mvhenten** [comment]
Hi, I agree that the API is clunky to say the least. When building this, I wanted to keep some options open, like adding "default" and "optional" to the spec. I've never gotten around this unfortunately.

I do not want to alter the original API due to backwards compatibility - I have quite a code base where I use this sometimes ( it has been my defense strategy in refactoring a big spaghetti mess I've inherited ).

However, I've been planning on adding a short-hand api for a while:

``` javascript
  var args = Validate.named(arguments, { number: 'whole', name: 'string' });
```

And 

``` javascript
  var args = Validate.positional(arguments, 'whole', 'string' );
```

Where named stands for "named arguments". Would this also resolve your issue?

cheers,

Matthijs

**Comment by mvhenten** [comment]
Please check https://github.com/mvhenten/validate-arguments-js/tree/issue-3-better-api

I've also removed the native forEach for browser compat.

**Comment by givankin** [comment]
Yes, looks good to me (though the changes in my PR didn't break backwards compatibility). 

I was also thinking of adding a universal method that would be "clever" about the passed arguments, in the jQuery manner, so something like this would be possible:

``` javascript
var validate = require('validate-arguments');
validate(arguments, 'string'); // uses isValidOfType
validate(arguments, { number: 'whole', name: 'string' }); // uses validateObject
validate(arguments, ['whole', { number: 'whole', name: 'string' }]); // uses validatePositional
```

In fact this is similar to what I do in my code, but IMO making it a part of the lib would be nice.

**Comment by mvhenten** [comment]
You are right, it did not break compat & test are good, sorry.
Should i merge the pull anyway? i can merge my branch later manually.

As for the validate function: I'd like it to be a method of the module, thus:

``` javascript
   var validate = require('validate-arguments').validate;
```

If you have some kind of implementation already...

**Comment by givankin** [comment]
Don't think you should merge this PR, your fork covers it already though in a little different way. I think
 you should merge it instead. As for the validate function, I will make another PR for that.

**Comment by mvhenten** [comment]
Ok merged to master, will publish as soon as I get in range of better
internet

**Comment by mvhenten** [comment]
I've refactored the code quite a bit - removes duplication and unneeded processing. Should also be more readable. Let me know if this works for you, I'll publish it then.

https://github.com/mvhenten/validate-arguments-js/tree/refactor-1-merge-functions

**Comment by givankin** [comment]
No, this won't work :(
Code is fine, but why change to LGPL?! 
Sadly it won't be approved in my corporate environment, meaning sticking to older version or an unexpected significant rewrite.

**Comment by mvhenten** [comment]
What license do you need? I am fine with BSD too.

**Comment by mvhenten** [comment]
I just copied a skeleton structure here :)=

**Comment by givankin** [comment]
BSD or MIT would be awesome

**Comment by givankin** [comment]
Updated to the new version, works just fine, the API is much cleaner now. Thanks!

**Comment by mvhenten** [comment]
Nice to hear! success with your endeavours.

On Fri, Mar 28, 2014 at 10:38 AM, Georgiy Ivankin
notifications@github.comwrote:

> Updated to the new version, works just fine, the API is much cleaner now.
> Thanks!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mvhenten/validate-arguments-js/pull/3#issuecomment-38901847
> .

## 

webdeveloper & consultant @technischepartij.nl
Mobile: +31 (0)630841238

Retiefstraat 51-III
1092VX Amsterdam
The Netherlands

**Pull request closed without merging**
